# Generated by Django 5.2 on 2026-09-07 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_num',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000, 'Phone number must be 10 digits'), django.core.validators.MaxValueValidator(9999999999, 'Phone number must be 10 digits')]),
        ),
    ]
